export const SAVE_ACCOUNT = "SAVE_ACCOUNT";
export const FETCH_ACCOUNTS = "FETCH_ACCOUNTS";
export const GET_ACCOUNT_INFORMATION = "GET_ACCOUNT_INFORMATION";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const REMOVE_ACCOUNT = "REMOVE_ACCOUNT";
export const CLEAR_ACCOUNT_ERROR = "CLEAR_ACCOUNT_ERROR";
export const SET_ACCOUNT_ERROR = "SET_ACCOUNT_ERROR";
