export const SAVE_ACCOUNT = "SAVE_ACCOUNT";
export const FETCH_ACCOUNTS = "FETCH_ACCOUNTS";
export const GET_ACCOUNT_INFORMATION = "GET_ACCOUNT_INFORMATION";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const REMOVE_ACCOUNT = "REMOVE_ACCOUNT";
