export const AUTHENTICATION_LOGIN = "AUTHENTICATION_LOGIN";
export const SET_AUTHENTICATION_ERROR = "SET_AUTHENTICATION_ERROR";
export const SET_AUTHENTICATION_TOKEN = "SET_AUTHENTICATION_TOKEN";
export const CLEAR_AUTHENTICATION_ERROR = "CLEAR_AUTHENTICATION_ERROR";
export const GET_AUTHENTICATED_CREDENTIALS = "GET_AUTHENTICATED_CREDENTIALS";
export const PURGE_AUTHENTICATION = "PURGE_AUTHENTICATION";
