export const SAVE_DEPARTMENT = "SAVE_DEPARTMENT";
export const FETCH_DEPARTMENTS = "FETCH_DEPARTMENTS";
export const GET_DEPARTMENT_INFORMATION = "GET_DEPARTMENT_INFORMATION";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const REMOVE_DEPARTMENT = "REMOVE_DEPARTMENT";
