export const SAVE_DESIGNATION = "SAVE_DESIGNATION";
export const FETCH_DESIGNATIONS = "FETCH_DESIGNATIONS";
export const GET_DESIGNATION_INFORMATION = "GET_DESIGNATION_INFORMATION";
export const UPDATE_DESIGNATION = "UPDATE_DESIGNATION";
export const REMOVE_DESIGNATION = "REMOVE_DESIGNATION";
