export const GENERATE_EMPLOYEE_CUSTOM_ID = "GENERATE_EMPLOYEE_CUSTOM_ID";
export const SAVE_EMPLOYEE = "SAVE_EMPLOYEE";
export const FETCH_EMPLOYEES = "FETCH_EMPLOYEES";
export const GET_EMPLOYEE_INFORMATION = "GET_EMPLOYEE_INFORMATION";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const REMOVE_EMPLOYEE = "REMOVE_EMPLOYEE";
